import { PF_EXTERNAL_ACCESSIBILITY, PF_EXTERNAL_DESIGN_COMPONENTS, PF_EXTERNAL_EXAMPLES_REACT_CORE, PF_EXTERNAL_EXAMPLES_TABLE } from './options.defaults';

const COMPONENT_DOCS = [
  `[@patternfly/AboutModal - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/about-modal/about-modal.md)`,
  `[@patternfly/AboutModal - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/about-modal/about-modal.md)`,
  `[@patternfly/AboutModal - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/AboutModal/examples/AboutModal.md)`,
  `[@patternfly/Accordion - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/accordion/accordion.md)`,
  `[@patternfly/Accordion - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/accordion/accordion.md)`,
  `[@patternfly/Accordion - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Accordion/examples/Accordion.md)`,
  `[@patternfly/ActionList - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/action-list/action-list.md)`,
  `[@patternfly/ActionList - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/action-list/action-list.md)`,
  `[@patternfly/ActionList - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ActionList/examples/ActionList.md)`,
  `[@patternfly/Alert - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/alert/alert.md)`,
  `[@patternfly/Alert - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/alert/alert.md)`,
  `[@patternfly/Alert - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Alert/examples/Alert.md)`,
  `[@patternfly/ApplicationLauncher - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/application-launcher/application-launcher.md)`,
  `[@patternfly/ApplicationLauncher - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/application-launcher/application-launcher.md)`,
  // `[@patternfly/ApplicationLauncher - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ApplicationLauncher/examples/ApplicationLauncher.md)`,
  `[@patternfly/Avatar - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/avatar/avatar.md)`,
  `[@patternfly/Avatar - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/avatar/avatar.md)`,
  `[@patternfly/Avatar - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Avatar/examples/Avatar.md)`,
  `[@patternfly/BackToTop - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/back-to-top/back-to-top.md)`,
  // `[@patternfly/BackToTop - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/back-to-top/back-to-top.md)`,
  `[@patternfly/BackToTop - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/BackToTop/examples/BackToTop.md)`,
  `[@patternfly/Backdrop - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/backdrop/backdrop.md)`,
  `[@patternfly/Backdrop - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/backdrop/backdrop.md)`,
  `[@patternfly/Backdrop - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Backdrop/examples/Backdrop.md)`,
  `[@patternfly/BackgroundImage - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/background-image/background-image.md)`,
  `[@patternfly/BackgroundImage - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/background-image/background-image.md)`,
  `[@patternfly/BackgroundImage - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/BackgroundImage/examples/BackgroundImage.md)`,
  `[@patternfly/Badge - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/badge/badge.md)`,
  `[@patternfly/Badge - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/badge/badge.md)`,
  `[@patternfly/Badge - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Badge/examples/Badge.md)`,
  `[@patternfly/Banner - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/banner/banner.md)`,
  `[@patternfly/Banner - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/banner/banner.md)`,
  `[@patternfly/Banner - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Banner/examples/Banner.md)`,
  `[@patternfly/Brand - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/brand/brand.md)`,
  `[@patternfly/Brand - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/brand/brand.md)`,
  `[@patternfly/Brand - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Brand/examples/Brand.md)`,
  `[@patternfly/Breadcrumb - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/breadcrumb/breadcrumb.md)`,
  `[@patternfly/Breadcrumb - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/breadcrumb/breadcrumb.md)`,
  `[@patternfly/Breadcrumb - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Breadcrumb/examples/Breadcrumb.md)`,
  `[@patternfly/Button - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/button/button.md)`,
  `[@patternfly/Button - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/button/button.md)`,
  `[@patternfly/Button - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Button/examples/Button.md)`,
  `[@patternfly/CalendarMonth - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/calendar-month/calendar-month.md)`,
  `[@patternfly/CalendarMonth - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/calendar-month/calendar-month.md)`,
  `[@patternfly/CalendarMonth - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/CalendarMonth/examples/CalendarMonth.md)`,
  `[@patternfly/Card - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/card/card.md)`,
  `[@patternfly/Card - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/card/card.md)`,
  `[@patternfly/Card - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Card/examples/Card.md)`,
  `[@patternfly/Checkbox - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/checkbox/checkbox.md)`,
  `[@patternfly/Checkbox - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/checkbox/checkbox.md)`,
  `[@patternfly/Checkbox - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Checkbox/examples/Checkbox.md)`,
  `[@patternfly/ChipDeprecated - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/chip/chip.md)`,
  `[@patternfly/ChipDeprecated - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/chip/chip.md)`,
  // `[@patternfly/ChipDeprecated - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ChipDeprecated/examples/ChipDeprecated.md)`,
  `[@patternfly/ClipboardCopy - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/clipboard-copy/clipboard-copy.md)`,
  `[@patternfly/ClipboardCopy - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/clipboard-copy/clipboard-copy.md)`,
  `[@patternfly/ClipboardCopy - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ClipboardCopy/examples/ClipboardCopy.md)`,
  `[@patternfly/CodeBlock - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/code-block/code-block.md)`,
  // `[@patternfly/CodeBlock - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/code-block/code-block.md)`,
  `[@patternfly/CodeBlock - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/CodeBlock/examples/CodeBlock.md)`,
  `[@patternfly/CodeEditor - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/code-editor/code-editor.md)`,
  `[@patternfly/CodeEditor - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/code-editor/code-editor.md)`,
  // `[@patternfly/CodeEditor - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/CodeEditor/examples/CodeEditor.md)`,
  `[@patternfly/Content - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/content/content.md)`,
  // `[@patternfly/Content - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/content/content.md)`,
  `[@patternfly/Content - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Content/examples/Content.md)`,
  `[@patternfly/DataList - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/data-list/data-list.md)`,
  // `[@patternfly/DataList - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/data-list/data-list.md)`,
  `[@patternfly/DataList - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DataList/examples/DataList.md)`,
  `[@patternfly/DatePicker - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/date-picker/date-picker.md)`,
  // `[@patternfly/DatePicker - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/date-picker/date-picker.md)`,
  `[@patternfly/DatePicker - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DatePicker/examples/DatePicker.md)`,
  // `[@patternfly/DateTimePicker - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/date-time-picker/date-time-picker.md)`,
  // `[@patternfly/DateTimePicker - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/date-time-picker/date-time-picker.md)`,
  // `[@patternfly/DateTimePicker - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DateTimePicker/examples/DateTimePicker.md)`,
  `[@patternfly/DescriptionList - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/description-list/description-list.md)`,
  // `[@patternfly/DescriptionList - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/description-list/description-list.md)`,
  `[@patternfly/DescriptionList - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DescriptionList/examples/DescriptionList.md)`,
  `[@patternfly/Divider - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/divider/divider.md)`,
  // `[@patternfly/Divider - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/divider/divider.md)`,
  `[@patternfly/Divider - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Divider/examples/Divider.md)`,
  `[@patternfly/DragAndDrop - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/drag-and-drop/drag.md)`,
  // `[@patternfly/DragAndDrop - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/drag-and-drop/drag-and-drop.md)`,
  // `[@patternfly/DragAndDrop - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DragAndDrop/examples/DragAndDrop.md)`,
  `[@patternfly/Drawer - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/drawer/drawer.md)`,
  // `[@patternfly/Drawer - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/drawer/drawer.md)`,
  `[@patternfly/Drawer - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Drawer/examples/Drawer.md)`,
  `[@patternfly/Dropdown - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/dropdown/dropdown.md)`,
  // `[@patternfly/Dropdown - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/dropdown/dropdown.md)`,
  `[@patternfly/Dropdown - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Dropdown/examples/Dropdown.md)`,
  `[@patternfly/DualListSelector - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/dual-list-selector/dual-list-selector.md)`,
  // `[@patternfly/DualListSelector - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/dual-list-selector/dual-list-selector.md)`,
  `[@patternfly/DualListSelector - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/DualListSelector/examples/DualListSelector.md)`,
  `[@patternfly/EmptyState - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/empty-state/empty-state.md)`,
  // `[@patternfly/EmptyState - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/empty-state/empty-state.md)`,
  `[@patternfly/EmptyState - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/EmptyState/examples/EmptyState.md)`,
  `[@patternfly/ExpandableSection - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/expandable-section/expandable-section.md)`,
  `[@patternfly/ExpandableSection - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/expandable-section/expandable-section.md)`,
  `[@patternfly/ExpandableSection - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ExpandableSection/examples/ExpandableSection.md)`,
  `[@patternfly/FileUpload - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/file-upload/file-upload.md)`,
  // `[@patternfly/FileUpload - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/file-upload/file-upload.md)`,
  `[@patternfly/FileUpload - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/FileUpload/examples/FileUpload.md)`,
  `[@patternfly/Form - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/form/forms.md)`,
  // `[@patternfly/Form - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/form/form.md)`,
  `[@patternfly/Form - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Form/examples/Form.md)`,
  `[@patternfly/FormControl - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/form-control/form-control.md)`,
  // `[@patternfly/FormControl - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/form-control/form-control.md)`,
  // `[@patternfly/FormControl - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/FormControl/examples/FormControl.md)`,
  `[@patternfly/FormSelect - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/form-select/form-select.md)`,
  // `[@patternfly/FormSelect - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/form-select/form-select.md)`,
  `[@patternfly/FormSelect - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/FormSelect/examples/FormSelect.md)`,
  `[@patternfly/HelperText - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/helper-text/helper-text.md)`,
  `[@patternfly/HelperText - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/helper-text/helper-text.md)`,
  `[@patternfly/HelperText - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/HelperText/examples/HelperText.md)`,
  `[@patternfly/Hint - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/hint/hint.md)`,
  // `[@patternfly/Hint - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/hint/hint.md)`,
  `[@patternfly/Hint - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Hint/examples/Hint.md)`,
  // `[@patternfly/Icon - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/icon/icon.md)`,
  // `[@patternfly/Icon - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/icon/icon.md)`,
  `[@patternfly/Icon - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Icon/examples/Icon.md)`,
  `[@patternfly/InlineEdit - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/inline-edit/inline-edit.md)`,
  // `[@patternfly/InlineEdit - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/inline-edit/inline-edit.md)`,
  // `[@patternfly/InlineEdit - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/InlineEdit/examples/InlineEdit.md)`,
  `[@patternfly/InputGroup - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/input-group/input-group.md)`,
  // `[@patternfly/InputGroup - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/input-group/input-group.md)`,
  `[@patternfly/InputGroup - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/InputGroup/examples/InputGroup.md)`,
  `[@patternfly/JumpLinks - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/jump-link/jump-link.md)`,
  `[@patternfly/JumpLinks - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/jump-links/jump-links.md)`,
  `[@patternfly/JumpLinks - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/JumpLinks/examples/JumpLinks.md)`,
  `[@patternfly/Label - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/label/label.md)`,
  `[@patternfly/Label - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/label/label.md)`,
  `[@patternfly/Label - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Label/examples/Label.md)`,
  `[@patternfly/List - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/list/list.md)`,
  // `[@patternfly/List - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/list/list.md)`,
  `[@patternfly/List - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/List/examples/List.md)`,
  `[@patternfly/LoginPage - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/login-page/login-page.md)`,
  // `[@patternfly/LoginPage - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/login-page/login-page.md)`,
  `[@patternfly/LoginPage - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/LoginPage/examples/LoginPage.md)`,
  `[@patternfly/Masthead - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/masthead/masthead.md)`,
  // `[@patternfly/Masthead - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/masthead/masthead.md)`,
  `[@patternfly/Masthead - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Masthead/examples/Masthead.md)`,
  `[@patternfly/Menu - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/menu/menu.md)`,
  `[@patternfly/Menu - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/menu/menu.md)`,
  `[@patternfly/Menu - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Menu/examples/Menu.md)`,
  `[@patternfly/MenuToggle - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/menu-toggle/menu-toggle.md)`,
  `[@patternfly/MenuToggle - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/menu-toggle/menu-toggle.md)`,
  `[@patternfly/MenuToggle - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/MenuToggle/examples/MenuToggle.md)`,
  `[@patternfly/Modal - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/modal/modal.md)`,
  `[@patternfly/Modal - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/modal/modal.md)`,
  `[@patternfly/Modal - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Modal/examples/Modal.md)`,
  `[@patternfly/Navigation - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/navigation/navigation.md)`,
  `[@patternfly/Navigation - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/navigation/navigation.md)`,
  // `[@patternfly/Navigation - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Navigation/examples/Navigation.md)`,
  `[@patternfly/NotificationBadge - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/notification-badge/notification-badge.md)`,
  // `[@patternfly/NotificationBadge - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/notification-badge/notification-badge.md)`,
  `[@patternfly/NotificationBadge - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/NotificationBadge/examples/NotificationBadge.md)`,
  `[@patternfly/NotificationDrawer - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/notification-drawer/notification-drawer.md)`,
  // `[@patternfly/NotificationDrawer - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/notification-drawer/notification-drawer.md)`,
  `[@patternfly/NotificationDrawer - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/NotificationDrawer/examples/NotificationDrawer.md)`,
  `[@patternfly/NumberInput - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/number%20input/number-input.md)`,
  // `[@patternfly/NumberInput - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/number-input/number-input.md)`,
  `[@patternfly/NumberInput - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/NumberInput/examples/NumberInput.md)`,
  `[@patternfly/OverflowMenu - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/overflow-menu/overflow-menu.md)`,
  // `[@patternfly/OverflowMenu - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/overflow-menu/overflow-menu.md)`,
  `[@patternfly/OverflowMenu - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/OverflowMenu/examples/OverflowMenu.md)`,
  `[@patternfly/Page - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/page/page.md)`,
  `[@patternfly/Page - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/page/page.md)`,
  `[@patternfly/Page - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Page/examples/Page.md)`,
  `[@patternfly/Pagination - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/pagination/pagination.md)`,
  // `[@patternfly/Pagination - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/pagination/pagination.md)`,
  `[@patternfly/Pagination - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Pagination/examples/Pagination.md)`,
  `[@patternfly/Panel - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/panel/panel.md)`,
  // `[@patternfly/Panel - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/panel/panel.md)`,
  `[@patternfly/Panel - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Panel/examples/Panel.md)`,
  `[@patternfly/Popover - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/popover/popover.md)`,
  // `[@patternfly/Popover - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/popover/popover.md)`,
  `[@patternfly/Popover - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Popover/examples/Popover.md)`,
  `[@patternfly/Progress - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/progress/progress.md)`,
  `[@patternfly/Progress - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/progress/progress.md)`,
  `[@patternfly/Progress - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Progress/examples/Progress.md)`,
  `[@patternfly/ProgressStepper - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/progress-stepper/progress-stepper.md)`,
  `[@patternfly/ProgressStepper - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/progress-stepper/progress-stepper.md)`,
  `[@patternfly/ProgressStepper - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ProgressStepper/examples/ProgressStepper.md)`,
  `[@patternfly/Radio - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/radio/radio.md)`,
  `[@patternfly/Radio - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/radio/radio.md)`,
  `[@patternfly/Radio - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Radio/examples/Radio.md)`,
  `[@patternfly/SearchInput - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/search-input/search-input.md)`,
  // `[@patternfly/SearchInput - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/search-input/search-input.md)`,
  `[@patternfly/SearchInput - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/SearchInput/examples/SearchInput.md)`,
  `[@patternfly/Select - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/select/select.md)`,
  // `[@patternfly/Select - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/select/select.md)`,
  `[@patternfly/Select - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Select/examples/Select.md)`,
  `[@patternfly/Sidebar - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/sidebar/sidebar.md)`,
  `[@patternfly/Sidebar - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/sidebar/sidebar.md)`,
  `[@patternfly/Sidebar - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Sidebar/examples/Sidebar.md)`,
  `[@patternfly/SimpleList - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/simple-list/simple-list.md)`,
  // `[@patternfly/SimpleList - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/simple-list/simple-list.md)`,
  `[@patternfly/SimpleList - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/SimpleList/examples/SimpleList.md)`,
  `[@patternfly/Skeleton - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/skeleton/skeleton.md)`,
  `[@patternfly/Skeleton - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/skeleton/skeleton.md)`,
  `[@patternfly/Skeleton - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Skeleton/examples/Skeleton.md)`,
  `[@patternfly/SkipToContent - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/skip-to-content/skip-to-content.md)`,
  `[@patternfly/SkipToContent - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/skip-to-content/skip-to-content.md)`,
  `[@patternfly/SkipToContent - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/SkipToContent/examples/SkipToContent.md)`,
  `[@patternfly/Slider - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/slider/slider.md)`,
  // `[@patternfly/Slider - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/slider/slider.md)`,
  `[@patternfly/Slider - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Slider/examples/Slider.md)`,
  `[@patternfly/Spinner - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/spinner/spinner.md)`,
  // `[@patternfly/Spinner - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/spinner/spinner.md)`,
  `[@patternfly/Spinner - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Spinner/examples/Spinner.md)`,
  `[@patternfly/Switch - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/switch/switch.md)`,
  `[@patternfly/Switch - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/switch/switch.md)`,
  `[@patternfly/Switch - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Switch/examples/Switch.md)`,
  `[@patternfly/Table - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/table/table.md)`,
  // `[@patternfly/Table - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/table/table.md)`,
  `[@patternfly/Table - Examples](${PF_EXTERNAL_EXAMPLES_TABLE}/Table/examples/Table.md)`,
  `[@patternfly/Tabs - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/tabs/tabs.md)`,
  `[@patternfly/Tabs - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/tabs/tabs.md)`,
  `[@patternfly/Tabs - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Tabs/examples/Tabs.md)`,
  `[@patternfly/TextArea - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/text-area/text-area.md)`,
  // `[@patternfly/TextArea - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/text-area/text-area.md)`,
  `[@patternfly/TextArea - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TextArea/examples/TextArea.md)`,
  `[@patternfly/TextInput - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/text-input/text-input.md)`,
  // `[@patternfly/TextInput - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/text-input/text-input.md)`,
  `[@patternfly/TextInput - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TextInput/examples/TextInput.md)`,
  `[@patternfly/TextInputGroup - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/text-input-group/text-input-group.md)`,
  // `[@patternfly/TextInputGroup - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/text-input-group/text-input-group.md)`,
  `[@patternfly/TextInputGroup - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TextInputGroup/examples/TextInputGroup.md)`,
  `[@patternfly/TileDeprecated - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/tile/tile.md)`,
  // `[@patternfly/TileDeprecated - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/tile-deprecated/tile-deprecated.md)`,
  // `[@patternfly/TileDeprecated - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TileDeprecated/examples/TileDeprecated.md)`,
  `[@patternfly/TimePicker - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/time%20picker/time-picker.md)`,
  // `[@patternfly/TimePicker - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/time-picker/time-picker.md)`,
  `[@patternfly/TimePicker - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TimePicker/examples/TimePicker.md)`,
  `[@patternfly/Timestamp - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/timestamp/timestamp.md)`,
  // `[@patternfly/Timestamp - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/timestamp/timestamp.md)`,
  `[@patternfly/Timestamp - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Timestamp/examples/Timestamp.md)`,
  `[@patternfly/Title - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/title/title.md)`,
  `[@patternfly/Title - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/title/title.md)`,
  `[@patternfly/Title - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Title/examples/Title.md)`,
  `[@patternfly/ToggleGroup - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/toggle-group/toggle-group.md)`,
  // `[@patternfly/ToggleGroup - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/toggle-group/toggle-group.md)`,
  `[@patternfly/ToggleGroup - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/ToggleGroup/examples/ToggleGroup.md)`,
  `[@patternfly/Toolbar - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/toolbar/toolbar.md)`,
  // `[@patternfly/Toolbar - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/toolbar/toolbar.md)`,
  `[@patternfly/Toolbar - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Toolbar/examples/Toolbar.md)`,
  `[@patternfly/Tooltip - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/tooltip/tooltip.md)`,
  `[@patternfly/Tooltip - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/tooltip/tooltip.md)`,
  `[@patternfly/Tooltip - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Tooltip/examples/Tooltip.md)`,
  `[@patternfly/TreeView - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/tree-view/tree-view.md)`,
  `[@patternfly/TreeView - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/tree-view/tree-view.md)`,
  `[@patternfly/TreeView - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/TreeView/examples/TreeView.md)`,
  `[@patternfly/Truncate - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/truncate/truncate.md)`,
  // `[@patternfly/Truncate - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/truncate/truncate.md)`,
  `[@patternfly/Truncate - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Truncate/examples/Truncate.md)`,
  `[@patternfly/Wizard - Design Guidelines](${PF_EXTERNAL_DESIGN_COMPONENTS}/wizard/wizard.md)`,
  // `[@patternfly/Wizard - Accessibility](${PF_EXTERNAL_ACCESSIBILITY}/wizard/wizard.md)`,
  `[@patternfly/Wizard - Examples](${PF_EXTERNAL_EXAMPLES_REACT_CORE}/Wizard/examples/Wizard.md)`
];

export { COMPONENT_DOCS };
